//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryEntitiesConnect : DbContext
    {
        public InventoryEntitiesConnect()
            : base("name=InventoryEntitiesConnect")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<StoreMovement> StoreMovements { get; set; }
        public virtual DbSet<StoreReturnDisparity> StoreReturnDisparities { get; set; }
        public virtual DbSet<Subcategory> Subcategories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<UseByYearVw> UseByYearVws { get; set; }
        public virtual DbSet<ProjectDate> ProjectDates { get; set; }
        public virtual DbSet<UserReview> UserReviews { get; set; }
    
        public virtual ObjectResult<sp_purchased_items_indate_Result> sp_purchased_items_indate(Nullable<System.DateTime> projectdate)
        {
            var projectdateParameter = projectdate.HasValue ?
                new ObjectParameter("projectdate", projectdate) :
                new ObjectParameter("projectdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_purchased_items_indate_Result>("sp_purchased_items_indate", projectdateParameter);
        }
    }
}
