//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Subcategories = new HashSet<Subcategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool RequiresRefrig { get; set; }
        public string Notes { get; set; }
        public byte CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
}
