//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMovement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreMovement()
        {
            this.StoreReturnDisparities = new HashSet<StoreReturnDisparity>();
        }
    
        public System.Guid Id { get; set; }
        public int PurchaseId { get; set; }
        public int LocationId { get; set; }
        public short ItemsOut { get; set; }
        public short ItemsReturned { get; set; }
        public System.DateTime TimeOut { get; set; }
        public Nullable<System.DateTime> TimeReturned { get; set; }
        public string Notes { get; set; }
        public int ProjectDateId { get; set; }
        public Nullable<System.Guid> CheckoutUserId { get; set; }
        public System.Guid CheckinUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Location Location { get; set; }
        public virtual ProjectDate ProjectDate { get; set; }
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreReturnDisparity> StoreReturnDisparities { get; set; }
    }
}
