//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreReturnDisparity
    {
        public int Id { get; set; }
        public int StoreMovementId { get; set; }
        public short ItemsReturned { get; set; }
        public string CheckinUserId { get; set; }
    
        public virtual StoreMovement StoreMovement { get; set; }
    }
}
