//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMovement
    {
        public StoreMovement()
        {
            this.StoreReturnDisparities = new HashSet<StoreReturnDisparity>();
        }
    
        public int Id { get; set; }
        public int PurchaseId { get; set; }
        public byte WardId { get; set; }
        public short ItemsOut { get; set; }
        public short ItemsReturned { get; set; }
        public System.DateTime TimeOut { get; set; }
        public Nullable<System.DateTime> TimeReturned { get; set; }
        public string Notes { get; set; }
        public string CheckoutUserId { get; set; }
        public string CheckinUserId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Purchase Purchase { get; set; }
        public virtual ICollection<StoreReturnDisparity> StoreReturnDisparities { get; set; }
    }
}
