//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedByProjectDate
    {
        public Nullable<int> UsedItemCount { get; set; }
        public int ItemSubcategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
