//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FijiProjectInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public byte[] SessionId { get; set; }
        public System.DateTime FirstViewTime { get; set; }
        public Nullable<System.DateTime> LasthChangeTime { get; set; }
        public int Updates { get; set; }
        public int Deletes { get; set; }
        public int Creates { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
